[CmdletBinding()]
param(
    [switch]$Configure,
    [switch]$Build
)

$ErrorActionPreference = "Stop"
$RepositoryRoot = Split-Path -Parent $PSScriptRoot
$EnvironmentFile = Join-Path $RepositoryRoot ".env"
$DockerExecutable = $null

Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::EnableVisualStyles()

function Show-GEDICorrectBanner {
    $BannerPath = Join-Path $RepositoryRoot "utils\ascii.txt"
    if (-not (Test-Path -LiteralPath $BannerPath -PathType Leaf)) {
        Write-Host "GEDICorrect v1.0.0" -ForegroundColor Cyan
        return
    }

    $BannerLines = @(Get-Content -LiteralPath $BannerPath)
    Write-Host ""
    foreach ($Line in $BannerLines) {
        Write-Host $Line -ForegroundColor Cyan
    }
    Write-Host ""
    Write-Host "GEDI geolocation correction | v1.0.0" -ForegroundColor DarkCyan
}

function Select-DataFolder {
    param(
        [string]$Description,
        [string]$InitialDirectory = ""
    )

    $Dialog = New-Object System.Windows.Forms.FolderBrowserDialog
    $Dialog.Description = $Description
    $Dialog.ShowNewFolderButton = $true
    if ($InitialDirectory -and (Test-Path -LiteralPath $InitialDirectory -PathType Container)) {
        $Dialog.SelectedPath = $InitialDirectory
    }

    $Result = $Dialog.ShowDialog()
    if ($Result -ne [System.Windows.Forms.DialogResult]::OK) {
        throw [System.OperationCanceledException]::new("Folder selection was cancelled.")
    }
    return $Dialog.SelectedPath
}

function Confirm-ExpectedFiles {
    param(
        [string]$Directory,
        [string]$Extension,
        [string]$Description
    )

    $FoundFile = Get-ChildItem -LiteralPath $Directory -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -ieq $Extension } |
        Select-Object -First 1
    if ($FoundFile) {
        return
    }

    Write-Host ""
    Write-Host "The selected $Description folder contains no $Extension files." -ForegroundColor Yellow
    while ($true) {
        $Response = ([string](Read-Host "Use this folder anyway? [Y]es / [N]o")).Trim().ToLowerInvariant()
        if ($Response -in @("y", "yes")) {
            return
        }
        if ($Response -in @("n", "no")) {
            throw [System.OperationCanceledException]::new(
                "Please restart GEDICorrect and select a different $Description folder."
            )
        }
        Write-Host "Please enter Y or N." -ForegroundColor Yellow
    }
}

function ConvertTo-EnvironmentValue {
    param([string]$Path)

    $NormalizedPath = $Path.Replace("\", "/").Replace("'", "\'")
    return "'$NormalizedPath'"
}

function Write-GEDICorrectEnvironment {
    $DocumentsDirectory = [Environment]::GetFolderPath("MyDocuments")
    $AlsDirectory = Select-DataFolder "Select the folder containing uncompressed ALS .las files." $DocumentsDirectory
    Confirm-ExpectedFiles $AlsDirectory ".las" "ALS"

    $InputDirectory = Select-DataFolder "Select the folder containing merged GEDI .gpkg files." $DocumentsDirectory
    Confirm-ExpectedFiles $InputDirectory ".gpkg" "GEDI input"

    $OutputDirectory = Select-DataFolder "Select or create the folder where GEDICorrect should save results." $DocumentsDirectory

    $ProcessorCount = [Math]::Max(1, [Math]::Min(8, [Environment]::ProcessorCount))
    $Lines = @(
        "# Generated by the GEDICorrect Windows launcher."
        "# Run Start-GEDICorrect.cmd again to reuse or change these folders."
        "GEDICORRECT_ALS_DIR=$(ConvertTo-EnvironmentValue $AlsDirectory)"
        "GEDICORRECT_INPUT_DIR=$(ConvertTo-EnvironmentValue $InputDirectory)"
        "GEDICORRECT_OUTPUT_DIR=$(ConvertTo-EnvironmentValue $OutputDirectory)"
        "GEDICORRECT_PORT=8501"
        "GEDICORRECT_CPUS=$ProcessorCount.0"
        "GEDICORRECT_MEMORY=16g"
        "GEDICORRECT_SHM_SIZE=2g"
        "GEDICORRECT_UID=10001"
        "GEDICORRECT_GID=10001"
    )
    $Utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($EnvironmentFile, $Lines, $Utf8WithoutBom)
}

function Get-EnvironmentSetting {
    param(
        [string]$Name,
        [string]$DefaultValue
    )

    if (-not (Test-Path -LiteralPath $EnvironmentFile -PathType Leaf)) {
        return $DefaultValue
    }
    $Match = Get-Content -LiteralPath $EnvironmentFile |
        Where-Object { $_ -match "^$([Regex]::Escape($Name))=" } |
        Select-Object -Last 1
    if (-not $Match) {
        return $DefaultValue
    }
    $Value = ($Match -split "=", 2)[1].Trim()
    if ($Value.Length -ge 2 -and $Value.StartsWith("'") -and $Value.EndsWith("'")) {
        return $Value.Substring(1, $Value.Length - 2).Replace("\'", "'")
    }
    if ($Value.Length -ge 2 -and $Value.StartsWith('"') -and $Value.EndsWith('"')) {
        return $Value.Substring(1, $Value.Length - 2)
    }
    return $Value
}

function Read-SavedConfigurationAction {
    $AlsDirectory = Get-EnvironmentSetting "GEDICORRECT_ALS_DIR" "(not configured)"
    $InputDirectory = Get-EnvironmentSetting "GEDICORRECT_INPUT_DIR" "(not configured)"
    $OutputDirectory = Get-EnvironmentSetting "GEDICORRECT_OUTPUT_DIR" "(not configured)"

    Write-Host ""
    Write-Host "GEDICorrect already has saved data folders:" -ForegroundColor Cyan
    Write-Host "  ALS:    $AlsDirectory"
    Write-Host "  GEDI:   $InputDirectory"
    Write-Host "  Output: $OutputDirectory"
    Write-Host ""

    while ($true) {
        $Response = ([string](Read-Host "Use these folders? [Y]es / [N]o, select again / [Q]uit (default: Y)")).Trim().ToLowerInvariant()
        if ($Response -in @("", "y", "yes")) {
            return "start"
        }
        if ($Response -in @("n", "no")) {
            return "configure"
        }
        if ($Response -in @("q", "quit", "exit")) {
            return "quit"
        }
        Write-Host "Please enter Y, N, or Q." -ForegroundColor Yellow
    }
}

function Invoke-DockerCommand {
    param(
        [string[]]$Arguments,
        [switch]$Quiet
    )

    $DockerPath = @($script:DockerExecutable) | Select-Object -First 1
    if (-not $DockerPath) {
        throw "Docker was not found. Install Docker Desktop for Windows, start it, and try again."
    }

    $StartParameters = @{
        FilePath = [string]$DockerPath
        ArgumentList = $Arguments
        Wait = $true
        NoNewWindow = $true
        PassThru = $true
    }
    $StandardOutput = $null
    $StandardError = $null
    if ($Quiet) {
        $StandardOutput = [System.IO.Path]::GetTempFileName()
        $StandardError = [System.IO.Path]::GetTempFileName()
        $StartParameters.RedirectStandardOutput = $StandardOutput
        $StartParameters.RedirectStandardError = $StandardError
    }

    try {
        $Process = Start-Process @StartParameters
        return $Process.ExitCode
    }
    finally {
        if ($StandardOutput) {
            Remove-Item -LiteralPath $StandardOutput -Force -ErrorAction SilentlyContinue
        }
        if ($StandardError) {
            Remove-Item -LiteralPath $StandardError -Force -ErrorAction SilentlyContinue
        }
    }
}

function Test-DockerReady {
    return (Invoke-DockerCommand -Arguments @("info") -Quiet) -eq 0
}

function Start-DockerDesktop {
    if (Test-DockerReady) {
        return
    }

    $DockerDesktop = Join-Path $Env:ProgramFiles "Docker\Docker\Docker Desktop.exe"
    if (-not (Test-Path -LiteralPath $DockerDesktop -PathType Leaf)) {
        throw "Docker Desktop is not running. Start Docker Desktop and try again."
    }

    Write-Host "Starting Docker Desktop..."
    Start-Process -FilePath $DockerDesktop
    for ($Attempt = 0; $Attempt -lt 90; $Attempt++) {
        Start-Sleep -Seconds 2
        if (Test-DockerReady) {
            return
        }
    }
    throw "Docker Desktop did not become ready within three minutes."
}

function Wait-ForGEDICorrect {
    param([int]$Port)

    $HealthUrl = "http://127.0.0.1:$Port/_stcore/health"
    Write-Host "Waiting for the GEDICorrect interface..."
    for ($Attempt = 0; $Attempt -lt 60; $Attempt++) {
        try {
            $Response = Invoke-WebRequest -Uri $HealthUrl -UseBasicParsing -TimeoutSec 2
            if ($Response.StatusCode -eq 200) {
                return
            }
        }
        catch {
            Start-Sleep -Seconds 2
        }
    }
    throw "GEDICorrect started, but its interface did not become ready. Run 'docker compose logs' for details."
}

try {
    if ($RepositoryRoot.StartsWith("\\")) {
        throw (
            "The Windows launcher cannot run from a WSL or network path: $RepositoryRoot`n`n" +
            "Copy or extract the complete GEDICorrect folder to a local Windows path, such as " +
            "C:\Users\YourName\GEDICorrect, and run Start-GEDICorrect.cmd there. " +
            "Do not run the launcher as administrator."
        )
    }
    Set-Location -LiteralPath $RepositoryRoot
    Show-GEDICorrectBanner

    if ((Test-Path -LiteralPath $EnvironmentFile -PathType Leaf) -and -not $Configure) {
        $ConfigurationAction = Read-SavedConfigurationAction
        if ($ConfigurationAction -eq "quit") {
            exit 0
        }
        if ($ConfigurationAction -eq "configure") {
            Write-GEDICorrectEnvironment
        }
    }
    else {
        Write-GEDICorrectEnvironment
    }

    $DockerCommand = @(
        Get-Command docker -CommandType Application -ErrorAction SilentlyContinue
    ) | Select-Object -First 1
    if (-not $DockerCommand) {
        throw "Docker was not found. Install Docker Desktop for Windows, start it, and try again."
    }
    $script:DockerExecutable = [string]$DockerCommand.Source
    Start-DockerDesktop

    if ((Invoke-DockerCommand -Arguments @("compose", "version") -Quiet) -ne 0) {
        throw "Docker Compose is unavailable. Update Docker Desktop and try again."
    }

    if ($Build) {
        Write-Host "Rebuilding and starting GEDICorrect..."
    }
    else {
        Write-Host "Starting GEDICorrect and checking the application image..."
    }
    Write-Host "The first build can take several minutes; later launches reuse Docker's build cache."
    $DockerExitCode = Invoke-DockerCommand -Arguments @("compose", "up", "--build", "--detach")
    if ($DockerExitCode -ne 0) {
        throw "Docker could not start GEDICorrect. Review the messages above for details."
    }

    $Port = [int](Get-EnvironmentSetting "GEDICORRECT_PORT" "8501")
    Wait-ForGEDICorrect $Port
    Start-Process "http://localhost:$Port"
    Write-Host ""
    Write-Host "GEDICorrect is running and will open in your browser." -ForegroundColor Green
    Write-Host "Use Stop-GEDICorrect.cmd when you finish."
    exit 0
}
catch [System.OperationCanceledException] {
    exit 0
}
catch {
    Write-Host "GEDICorrect error: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
